### ISSUE TITLE
Some missing features / documentation?

### ISSUE THREAD

**Issue by DelcoigneYves** [collectiveuk/packages#1]
Hi there!

First of all, thank you for sharing this package! I believe the dynamic route registry is very nice, and currently missing in other popular routing packages.

I'd like to try out your package, but I stumble against some open points I would like to get your input on:
- How to add NavigatorObservers? I think these work pretty similarly like your interceptors, but it would be good to add support for these as well, as other packages tend to integrate with this. For example, we are using the Talker logging package, which provides such an observer.
- When should we override the builder method, and when the pageBuilder? What's the difference?
- How should we specify / override the page transitions?
- How can we support nested routing in a modal sheet with this package?

🙏

**Comment by JaspervanRiet** [comment]
Hello! Let me go through these one by one.

> How to add NavigatorObservers? I think these work pretty similarly like your interceptors, but it would be good to add support for these as well, as other packages tend to integrate with this. For example, we are using the Talker logging package, which provides such an observer.

We currently do not support them. The reason for that is they show funky behaviour when nesting navigators. You cannot just have one observer on DuckRouter, we would need to facilitate an API that allows you to hook into the nested `Navigator` on the `StatefulLocation`. I feel that goes against DuckRouter's simplicity. I'd currently advise to use `onNavigate` on DuckRouter to listen to new navigations, and then log from there. Same with the Sentry NavigatorObserver, or anything else. That's how we do analytics. 

However, if that really doesn't work, we can look into supporting it.

>When should we override the builder method, and when the pageBuilder? What's the difference?

> How should we specify / override the page transitions?

These questions are related! I've just made #2 to address this. Basically, you can extend [Page](https://api.flutter.dev/flutter/widgets/Page-class.html) and do whatever you want. I think DuckRouter can provide you more help here. Created #2

> How can we support nested routing in a modal sheet with this package?
Could you be a little bit more specific? We have quite a large number of modal flows in our application and we are able to do so by using `navigate`.

**Comment by JaspervanRiet** [comment]
Should actually be quite a bit easier :)

First of all, see this SO answer for some inspiration on how to extend `Page`: https://stackoverflow.com/a/76264049

Once you've got that, say at location `MyCoolModalLocation`, you can navigate to it like this:

```dart
DuckRouter.of(context).navigate(to: MyCoolModalLocation(), root: true);
```

The `root` is important, that allows you to navigate from the root navigator. If you are not inside a stateful location like a bottom bar, you can skip it.

Then inside the modal you can navigate as normal.

**Comment by DelcoigneYves** [comment]
Thanks for the info, I’ll give it a try!

Keep up the good work 🎉

**Comment by DelcoigneYves** [comment]
Just wanted to give an update: I found that, when you are using a non-fullscreen modal, a StatefulLocation is really needed, as otherwise any nested navigation will just open as a full screen instead of in the modal (even when adding a DuckShell manually to the PageBuilder).

**Comment by JaspervanRiet** [comment]
Good to know @DelcoigneYves. Any issues or does it work fine?

**Comment by DelcoigneYves** [comment]
Works perfectly, and quite a lot easier than what we needed to do with auto_route :-)

**Comment by JaspervanRiet** [comment]
That's awesome to hear!
