### ISSUE TITLE
Some confusion with Location definition

### ISSUE THREAD

**Issue by DelcoigneYves** [collectiveuk/packages#11]
Hi there!

When I was experimenting with the different Locations, I found that there implementation was sometimes a bit confusing. I'll use this issue to give some (hopefully constructive) feedback 😊 

- This is probably related to #3 : when overriding the `pageBuilder` method and providing a custom Page object, we **need** to add the `name` property. The `DuckShell.reset()` method works with this name, to reset the Stack to the root location. When not providing this and calling `root`, the user just sees a blank screen (since all pages are popped). I'm wondering if your PR #10 would not experience the same issue?
- When creating a StatefulLocation with a custom Page, I needed to duplicate the GlobalKey and the `state` getter, to be able to use it in the DuckShell added. I'm hoping this could be solved a bit more elegantly.
- Continuing with the previous StatefulLocation, when overriding `pageBuilder`, we are still required to implement `childBuilder`, even though it is not being used.
- I'm wondering about the purpose of the extra `StatefulChildLocation` class. Since it does not really do anything apart from being held in a list for use in the DuckShell, I wonder if this could not just be a list of `Location`s? And if it does have its purpose, why is the `builder` made required? For context: related to my previous questions in #7 , I created a `StatefulChildLocation` with a custom Page, that I could open either as a root point in a `StatefulLocation`, or just navigate to like a normal page navigation.

Overall, everything I wanted / needed for my app is working, these are just some topics that I believe when fixed, could make the package even easier to use 😉

**Comment by JaspervanRiet** [comment]
Hi, I'm trying to understand your feedback but I'm afraid I'm having a hard time:

> This is probably related to https://github.com/collectiveuk/packages/issues/3 : when overriding the pageBuilder method and providing a custom Page object, we need to add the name property. The DuckShell.reset() method works with this name, to reset the Stack to the root location. When not providing this and calling root, the user just sees a blank screen (since all pages are popped). I'm wondering if your PR https://github.com/collectiveuk/packages/pull/10 would not experience the same issue?

Do you have a code example of how I can replicate this? 

> When creating a StatefulLocation with a custom Page, I needed to duplicate the GlobalKey and the state getter, to be able to use it in the DuckShell added. I'm hoping this could be solved a bit more elegantly.

Do you have a code example for this one too?

> Continuing with the previous StatefulLocation, when overriding pageBuilder, we are still required to implement childBuilder, even though it is not being used.

I think something is going wrong with this location. `pageBuilder` on a StatefulLocation should not be overridden. A StatefulLocation should have children, and those should override `pageBuilder`. I need to investigate what we can do here to stop this confusing situation. 

> I'm wondering about the purpose of the extra StatefulChildLocation class. Since it does not really do anything apart from being held in a list for use in the DuckShell, I wonder if this could not just be a list of Locations? And if it does have its purpose, why is the builder made required? For context: related to my previous questions in https://github.com/collectiveuk/packages/issues/7 , I created a StatefulChildLocation with a custom Page, that I could open either as a root point in a StatefulLocation, or just navigate to like a normal page navigation.

I think you're right. It definitely had a purpose earlier in development, but that use is now gone. Good spot! That's very nice, we can simplify our API.

**Comment by DelcoigneYves** [comment]
You can find my experimentation project [here](https://github.com/DelcoigneYves/duckrouter-example).

You can find the StatefulLocation in question [on this line](https://github.com/DelcoigneYves/duckrouter-example/blob/3cf37ba03fc2b850af5e3975dd926c04c5de64d3/lib/presentation/routes/routes.dart#L91).

To replicate the issue with the root method, just remove the name property from the NestedMainRoute [here](https://github.com/DelcoigneYves/duckrouter-example/blob/3cf37ba03fc2b850af5e3975dd926c04c5de64d3/lib/presentation/routes/routes.dart#L129).

To replicate the flow, start the app -> open second screen -> open nested screen -> open second screen -> Root.

It might very well be possible I made a mistake getting here! Let me know what I missed 🙏

**Comment by DelcoigneYves** [comment]
Thanks, I appreciate the quick feedback loop!

**Comment by JaspervanRiet** [comment]
Changes are live, your example project should now be easy to implement. Thanks!

**Comment by DelcoigneYves** [comment]
Hi @JaspervanRiet 

Thanks for the patience and effort!

However, I believe only my last question has been resolved (`StatefulChildLocation` removed). The other questions remain unanswered for me. I still need to override the `pageBuilder` in `StatefulLocation` to be able to provide a custom transition (either with my own `CustomPage`, or with the new `DuckPage`), as otherwise I do not get the desired result. Due to this, I also need to add my own DuckShell, and override the GlobalKey and state property from the abstract `StatefulChildLocation`.

Also the `popUntil` method has the same problem as the previous `root` method: when the name has not been added to the custom Page object, we are not possible to pop to this Location. This should either be clear from the usage, or can be described in the documentation.

**Comment by DelcoigneYves** [comment]
Questions answered in #21
