### ISSUE TITLE
Reset stack and add page

### ISSUE THREAD

**Issue by DelcoigneYves** [collectiveuk/packages#18]
Is there any way to just remove all the current pages, and push a new page? Scenario: logging out / deactivating the app.

**Comment by JaspervanRiet** [comment]
It seems clear that we need to bring back `root`, it was very useful and removed too quickly in #14. Then on top of that, like #17 mentions, we need to improve the interface of `popUntil` because currently you need to instantiate a new location and it's not very versatile.
