### ISSUE TITLE
onPopPage is deprecated

### ISSUE THREAD

**Issue by DelcoigneYves** [collectiveuk/packages#26]
Hi there!

Just when I thought this package was feature-complete, the new Flutter update 3.24.0 changes the Navigator's API 😅 

Documentation for reference: https://docs.flutter.dev/release/breaking-changes/navigator-and-page-api

Basically, the `onPopPage` should now only be used for cleaning up the page's stack. 

However, the change also does not send the popped Route's result back to the callback, so we cannot complete the `LocationState`'s `Completer` (and thus we are unable to correctly send the navigation result back to the caller).

I tried updating it to the new API, but I'm a bit lost on how to now correctly send the result back, so I'm calling on the hive mind for any suggestions ;)

**Comment by DelcoigneYves** [comment]
Issue for go_router dealing with the same: https://github.com/flutter/flutter/issues/152504

**Comment by JaspervanRiet** [comment]
Closed in #28
