### ISSUE TITLE
feat: include `NoTransitionPage<T>` that uses`DuckPage<T>` 

### ISSUE THREAD

**Issue by Luckey-Elijah** [collectiveuk/packages#29]
Hi, thanks for the great package!

I would like the ability to quickly build custom page transitions as easily as it was with `go_router`. Currently I use a `class CustomTransitionPage<T> extends Page<T> { .. }` that is mostly adapted from [`go_router`'s `CustomTransitionPage`](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/pages/custom_transition_page.dart#L11) and a `NoTransitionPage` that uses the following transition builder:

```dart
Widget noTransitionBuilder(
  BuildContext _,
  Animation<double> __,
  Animation<double> ___,
  Widget child,
) => child;
```

Would is be possible to include something similar in `duck_router` directly so that writing custom pages would be simpler for 
the getter `LocationPageBuilder? get pageBuilder`?

**Comment by Luckey-Elijah** [comment]
I discovered the `DuckPage` but didn't realize it was for custom pages. I'll use that!

**Comment by Luckey-Elijah** [comment]
leaving this here for anyone else needing it:
```dart

class NoTransitionPage<T> extends DuckPage<T> {
  const NoTransitionPage({
    required super.child,
    required super.name,
    super.arguments,
    super.restorationId,
    super.key,
  }) : super(
          transitionsBuilder: noTransitionBuilder,
          transitionDuration: Duration.zero,
          reverseTransitionDuration: Duration.zero,
        );
}

Widget noTransitionBuilder(
  BuildContext _,
  Animation<double> __,
  Animation<double> ___,
  Widget child,
) => child;
```

**Comment by JaspervanRiet** [comment]
That's the trick indeed, thanks for documenting your problem :)
