### ISSUE TITLE
[Bug] BackButtonDispatcher priority

### ISSUE THREAD

**Issue by clragon** [collectiveuk/packages#5]
`DuckShellState` has a typo that prevents it from correctly calling `takePriority` on its child back button dispatchers.
The function is missing the parenthese to actually execute the call.

The issue occurs [here](
https://github.com/collectiveuk/packages/blob/2abeb5a15c8508b9c64676ef2b27a43cd71edd32/flutter/packages/duck_router/lib/src/shell.dart#L106).

**Comment by JaspervanRiet** [comment]
Thank you!
